apiVersion: batch/v1
kind: Job
metadata:
  name: kfp-run-job
  labels:
    pipelines.kubeflow.org/v2_component: 'true'
spec:
  template:
    {{- include "product-recommender-system.pipeline-job-template" . | nindent 4 }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kfp-run-cronjob
  labels:
    pipelines.kubeflow.org/v2_component: 'true'
spec:
  schedule: "0 0 * * *"  # Run daily at midnight
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        {{- include "product-recommender-system.pipeline-job-template" . | nindent 8 }}
